import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <div className="min-h-screen flex flex-col">
        <Header />

        <main className="flex-1">{children}</main>
      </div>

      <SanityLive />
    </ClerkProvider>
  );
}
